### ISSUE TITLE
Git - practice with VSCode

### ISSUE THREAD

**Issue by ilovewine** [joannapolec/mentoring#8]
Install the following extensions:
1. Name: Git Graph
Id: mhutchie.git-graph
Description: View a Git Graph of your repository, and perform Git actions from the graph.
Version: 1.30.0
Publisher: mhutchie
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph

2. Name: Git Extension Pack
Id: donjayamanne.git-extension-pack
Description: Popular Visual Studio Code extensions for Git
Version: 0.1.3
Publisher: Don Jayamanne
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=donjayamanne.git-extension-pack

and see how they work, especially to GitLens and Git Graph - they are veru helpful :)

After familiarizing yourself with their capabilities, please do the following:

- [x] create some changes in your project
- [x] using the source control panel (ctrl+shift+g g) commit your changes
- [x] push them!
- [x] locate the git graph button in the source panel and interact with it
- [x] paste below a screenshot of how git graph looks like (1)

**Comment by joannapolec** [comment]
![Image](https://github.com/joannapolec/mentoring/assets/130462998/bfbe541a-45ae-4f8c-a087-8e3acc51bd99)
